CREATE TABLE users_form (
                            id SERIAL PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            email VARCHAR(100) UNIQUE NOT NULL,
                            password VARCHAR(255) NOT NULL,
                            batch VARCHAR(20) NOT NULL,
                            gender VARCHAR(20) NOT NULL,
                            dob DATE NOT NULL,
                            region VARCHAR(100),
                            community VARCHAR(50),
                            mobile_no BIGINT UNIQUE NOT NULL,
                            blood_group VARCHAR(10),
                            nationality VARCHAR(50),
                            specialization VARCHAR(100),
                            permanent_address TEXT,
                            guardian_address TEXT,
                            purpose_of_studying_course TEXT,
                            sports_achievement TEXT,
                            extra_curricular TEXT,
                            online_course TEXT,
                            referred_by VARCHAR(100),
                            created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);